info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    zuulserver: /self/**
    ad-enhancer-service: /adEnhance/**

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchReqistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}